"use client";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { QueryClientProvider } from "react-query";
import queryClient from "../queryClient";

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "onboarding test",
//   description: "Generated by MUBARAQ AKANBI",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <QueryClientProvider client={queryClient}>
        <body className={inter.className}>{children}</body>
      </QueryClientProvider>
    </html>
  );
}
